from typing import Literal, Optional, TypedDict


CopywriterMode = Literal["local", "groq"]

class GraphState(TypedDict):
    source_material: str #raw input from user(url or text)
    source_of_truth: Optional[str] #extracted content by agent 1(Researcher )
    ambiguity_flags: list[str] #ambiguous statements found in source material
    target_audience: Optional[str] #target audience extracted by researcher
    value_proposition: Optional[str] #core value proposition extracted by researcher
    draft_copy: Optional[str] #draft copy generated by agent 2(copywriter)
    social_draft: Optional[str] #social media thread generated by copywriter
    email_draft: Optional[str] #email campaign generated by copywriter
    editor_feedback: Optional[str] #feedback from the editor(agent 3)
    is_approved: bool #approval status of the draft copy
    revision_count: int #how many rewrite cycles were executed
    copywriter_mode: CopywriterMode #runtime mode selected from UI
    copywriter_runtime_note: Optional[str] #status or fallback note for UI chat feed