from typing import TypedDict, Optional

class GraphState(TypedDict):
    source_material: str #raw input from user(url or text)
    source_of_truth: Optional[str] #extracted content by agent 1(Researcher )
    draft_copy: Optional[str] #draft copy generated by agent 2(copywriter)
    editor_feedback: Optional[str] #feedback from the editor(agent 3)
    is_approved: bool #approval status of the draft copy